#!/usr/bin/bash

set -e

readonly DOCKER_USER="palm"
readonly CONTAINER_NAME="palm"
readonly PWD=`pwd`

docker run -it \
    -v "${PWD}:/home/${DOCKER_USER}/palm" \
    --name "${CONTAINER_NAME}" palm
