#!/usr/bin/bash
set -e

readonly DOCKER_IMAGE_NAME="palm"
readonly DOCKER_FILE="docker/Dockerfile"
readonly DOCKER_USER="palm"

docker build \
    -t $DOCKER_IMAGE_NAME \
    -f $DOCKER_FILE \
    --build-arg=USERNAME="$DOCKER_USER" \
    . 1>&2
